version: "3.8"
services:
    proxy:
        container_name: Ozon-front
        build:
            context: ../..
            dockerfile: .deploy/docker/dockerfiles/dockerfile
        networks:
            - network
        ports:
            - 80:80
