FROM node:latest AS build-stage

WORKDIR /var/www/html

# Copy project
COPY --chown=www-data:www-data . /var/www/html

RUN npm install --production
RUN npm run build

FROM nginx:latest

COPY --from=build-stage /var/www/html /usr/share/nginx/html

RUN rm /etc/nginx/nginx.conf
COPY .deploy/nginx/nginx.conf /etc/nginx/
RUN rm /etc/nginx/conf.d/default.conf
COPY .deploy/nginx/api.conf /etc/nginx/conf.d/
